Add SonarQube

diff --git a/.cirrus.default.yml b/.cirrus.default.yml
--- a/.cirrus.default.yml
+++ b/.cirrus.default.yml
@@ -187,89 +187,89 @@ validate_task:
     slack_notification_script: |
       source slack-failure-notification "Cirrus CI build failure on pipeline: $CIRRUS_PIPELINE_NAME"
 
-qa_connectedModeSonarQube_task:
-  #  name: "Run ITs for Connected Mode with SonarQube"
-  depends_on:
-    - build
-  <<: *ONLY_IF_EXCEPT_NIGHTLY
-  eks_container:
-    <<: *BUILDER_CONTAINER_DEFINITION
-    cpu: 4
-    memory: 16G
-    type: m6a.large
-  env:
-    ARTIFACTORY_API_KEY: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
-    GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]
-    DISPLAY: :10
-    MAVEN_OPTS: -Xmx3072m
-  matrix:
-    - env:
-        SQ_VERSION: 'LATEST_RELEASE[9.9]'
-        QA_CATEGORY: 'LATEST_RELEASE_99'
-    - env:
-        SQ_VERSION: 'LATEST_RELEASE'
-        QA_CATEGORY: 'LATEST_RELEASE'
-    - env:
-        SQ_VERSION: 'DEV'
-        QA_CATEGORY: 'DEV'
-  <<: *SETUP_MAVEN_CACHE_QA
-  <<: *SETUP_ORCHESTRATOR_CACHE
-  download_staged_update_site_script: |
-    set -euo pipefail
-    source cirrus-env QA
-    source .cirrus/set_maven_build_version $BUILD_NUMBER
-    mvn -B -e -V dependency:unpack \
-      -Declipse.p2.mirrors=false \
-      -Dtycho.mode=maven \
-      -Dartifact=org.sonarsource.sonarlint.eclipse:org.sonarlint.eclipse.site:${PROJECT_VERSION}:zip \
-      -DoutputDirectory=${CIRRUS_WORKING_DIR}/staged-repository
-  prepare_background_script: |
-    set -euo pipefail
-    /etc/init.d/xvfb start
-    metacity --sm-disable --replace &
-    sleep 10 # give metacity some time to start
-    echo 'Recording tests on video'
-    ffmpeg -loglevel warning -f x11grab -video_size 1920x1080 -i ${DISPLAY} -codec:v libx264 -r 12 ${CIRRUS_WORKING_DIR}/recording_${QA_CATEGORY}.mp4
-  run_its_script: |
-    echo "Run Maven ITs for Connected Mode with SonarQube on Eclipse 2024-03 / 4.31 (latest Java 17) and Server ${SQ_VERSION}"
-    cd its/
-    mvn -B -e -V org.jacoco:jacoco-maven-plugin:prepare-agent verify \
-      -s ${HOME}/.m2/settings-public-auth.xml \
-      -P coverage,\!standaloneMode,\!connectedModeSc,\!cdtIntegration \
-      -Declipse.p2.mirrors=false \
-      -Dtarget.platform=latest-java-17_e431 \
-      -Dtycho.localArtifacts=ignore \
-      -Dsonarlint-eclipse.p2.url="file://${CIRRUS_WORKING_DIR}/staged-repository" \
-      -Dsonar.runtimeVersion=${SQ_VERSION} \
-      -Djacoco.append=true \
-      -Djacoco.destFile=${CIRRUS_WORKING_DIR}/it-coverage.exec
-    mv ${CIRRUS_WORKING_DIR}/it-coverage.exec ${CIRRUS_WORKING_DIR}/it-coverage-${QA_CATEGORY}.exec
-  cleanup_before_cache_script: cleanup_maven_repository
-  always:
-    stop_recording_script: |
-      pkill -SIGINT -f ffmpeg
-      while pgrep ffmpeg >/dev/null; do sleep 1; done
-      /etc/init.d/xvfb stop
-    test_recording_artifacts:
-      path: "${CIRRUS_WORKING_DIR}/recording_${QA_CATEGORY}.mp4"
-    jacoco_it_sq_artifacts:
-      path: "${CIRRUS_WORKING_DIR}/it-coverage*.exec"
-    mvn_startTestLog_artifacts:
-      path: "${CIRRUS_WORKING_DIR}/its/**/target/work/configuration/*.log"
-    mvn_runTestLog_artifacts:
-      path: "${CIRRUS_WORKING_DIR}/its/**/target/work/data/.metadata/.log"
-  on_failure:
-    xvfb_log_artifacts:
-      path: "${CIRRUS_WORKING_DIR}/Xvfb.out"
-    reports_artifacts:
-      path: "**/reports/**/*"
-    junit_artifacts:
-      paths:
-      - "**/test-results/**/*.xml"
-      - "**/target/surefire-reports/TEST-*.xml"
-      format: junit
-    slack_notification_script: |
-      source slack-failure-notification "Cirrus CI build failure on pipeline: $CIRRUS_PIPELINE_NAME"
+#qa_connectedModeSonarQube_task:
+#  #  name: "Run ITs for Connected Mode with SonarQube"
+#  depends_on:
+#    - build
+#  <<: *ONLY_IF_EXCEPT_NIGHTLY
+#  eks_container:
+#    <<: *BUILDER_CONTAINER_DEFINITION
+#    cpu: 4
+#    memory: 16G
+#    type: m6a.large
+#  env:
+#    ARTIFACTORY_API_KEY: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
+#    GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]
+#    DISPLAY: :10
+#    MAVEN_OPTS: -Xmx3072m
+#  matrix:
+#    - env:
+#        SQ_VERSION: 'LATEST_RELEASE[9.9]'
+#        QA_CATEGORY: 'LATEST_RELEASE_99'
+#    - env:
+#        SQ_VERSION: 'LATEST_RELEASE'
+#        QA_CATEGORY: 'LATEST_RELEASE'
+#    - env:
+#        SQ_VERSION: 'DEV'
+#        QA_CATEGORY: 'DEV'
+#  <<: *SETUP_MAVEN_CACHE_QA
+#  <<: *SETUP_ORCHESTRATOR_CACHE
+#  download_staged_update_site_script: |
+#    set -euo pipefail
+#    source cirrus-env QA
+#    source .cirrus/set_maven_build_version $BUILD_NUMBER
+#    mvn -B -e -V dependency:unpack \
+#      -Declipse.p2.mirrors=false \
+#      -Dtycho.mode=maven \
+#      -Dartifact=org.sonarsource.sonarlint.eclipse:org.sonarlint.eclipse.site:${PROJECT_VERSION}:zip \
+#      -DoutputDirectory=${CIRRUS_WORKING_DIR}/staged-repository
+#  prepare_background_script: |
+#    set -euo pipefail
+#    /etc/init.d/xvfb start
+#    metacity --sm-disable --replace &
+#    sleep 10 # give metacity some time to start
+#    echo 'Recording tests on video'
+#    ffmpeg -loglevel warning -f x11grab -video_size 1920x1080 -i ${DISPLAY} -codec:v libx264 -r 12 ${CIRRUS_WORKING_DIR}/recording_${QA_CATEGORY}.mp4
+#  run_its_script: |
+#    echo "Run Maven ITs for Connected Mode with SonarQube on Eclipse 2024-03 / 4.31 (latest Java 17) and Server ${SQ_VERSION}"
+#    cd its/
+#    mvn -B -e -V org.jacoco:jacoco-maven-plugin:prepare-agent verify \
+#      -s ${HOME}/.m2/settings-public-auth.xml \
+#      -P coverage,\!standaloneMode,\!connectedModeSc,\!cdtIntegration \
+#      -Declipse.p2.mirrors=false \
+#      -Dtarget.platform=latest-java-17_e431 \
+#      -Dtycho.localArtifacts=ignore \
+#      -Dsonarlint-eclipse.p2.url="file://${CIRRUS_WORKING_DIR}/staged-repository" \
+#      -Dsonar.runtimeVersion=${SQ_VERSION} \
+#      -Djacoco.append=true \
+#      -Djacoco.destFile=${CIRRUS_WORKING_DIR}/it-coverage.exec
+#    mv ${CIRRUS_WORKING_DIR}/it-coverage.exec ${CIRRUS_WORKING_DIR}/it-coverage-${QA_CATEGORY}.exec
+#  cleanup_before_cache_script: cleanup_maven_repository
+#  always:
+#    stop_recording_script: |
+#      pkill -SIGINT -f ffmpeg
+#      while pgrep ffmpeg >/dev/null; do sleep 1; done
+#      /etc/init.d/xvfb stop
+#    test_recording_artifacts:
+#      path: "${CIRRUS_WORKING_DIR}/recording_${QA_CATEGORY}.mp4"
+#    jacoco_it_sq_artifacts:
+#      path: "${CIRRUS_WORKING_DIR}/it-coverage*.exec"
+#    mvn_startTestLog_artifacts:
+#      path: "${CIRRUS_WORKING_DIR}/its/**/target/work/configuration/*.log"
+#    mvn_runTestLog_artifacts:
+#      path: "${CIRRUS_WORKING_DIR}/its/**/target/work/data/.metadata/.log"
+#  on_failure:
+#    xvfb_log_artifacts:
+#      path: "${CIRRUS_WORKING_DIR}/Xvfb.out"
+#    reports_artifacts:
+#      path: "**/reports/**/*"
+#    junit_artifacts:
+#      paths:
+#      - "**/test-results/**/*.xml"
+#      - "**/target/surefire-reports/TEST-*.xml"
+#      format: junit
+#    slack_notification_script: |
+#      source slack-failure-notification "Cirrus CI build failure on pipeline: $CIRRUS_PIPELINE_NAME"
 
 qa_connectedModeSonarCloud_task:
   #  name: "Run ITs for Connected Mode with SonarCloud"
